### ISSUE TITLE
Can't use with xcode

### ISSUE THREAD

**Issue by JustinM1** [jakeheis/Flock#9]
with the addition of CNMSSH, xocde cant build the project.

<img width="259" alt="snmssh build errors" src="https://cloud.githubusercontent.com/assets/18277828/26424706/28f662fa-40a0-11e7-832b-fc0700a06ba6.png">

**Comment by jakeheis** [comment]
Thanks for reporting the issue! Fixed in 9bceca3; rather than using `swift package generate-xcodeproj`, use `./bin/genxc`

**Comment by JustinM1** [comment]
thanks for the update. However, flock --build still doesn't work.

`Linking ./.build/debug/Flockfile
ld: library not found for -lssh2 for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures`

**Comment by jakeheis** [comment]
You need to install libssh2 with Homebrew (`brew install libssh2`) so Flock can link against the library. I believe there's a way to have SPM provide this hint, so I'll implement that in CSSH https://github.com/jakeheis/CSSH/issues/1
